service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

custom:
  serviceName: users
  contextPath: /v1/${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/framework/functions
functions:
  - ${file(${self:custom.funcDir}/users.yml)}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
