service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-1'
  memorySize: 512
  apiGateway:
    restApiId: s80vwfaita
    restApiRootResourceId: /

custom:
  serviceName: users
  contextPath: api/v1/${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/4-framework/functions
functions:
  createUser:
    handler: ${self:custom.funcDir}/createUser.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: post
          cors:
            origin: '*'
            headers: '*'
  viewUser:
    handler: ${self:custom.funcDir}/viewUser.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{user_id}
          method: get
          cors:
            origin: '*'
            headers: '*'
  removeUser:
    handler: ${self:custom.funcDir}/removeUser.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{user_id}
          method: delete
          cors:
            origin: '*'
            headers: '*'
  updateUser:
    handler: ${self:custom.funcDir}/updateUser.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{user_id}
          method: put
          cors:
            origin: '*'
            headers: '*'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
