name: "Migrate Sequelize"
description: ""
inputs:
  db-name:
    description: 'campus_hub'
    required: true
runs:
  using: "composite"
  steps:
    - name: AWS - SSM Get Parameters
      uses: dkershner6/aws-ssm-getparameters-action@v1
      with:
          parameterPairs: "
              /ifsp/infra/EC2-PS/host = AWS_DB_HOST,
              /ifsp/infra/EC2-PS/port = AWS_DB_PORT,
              /ifsp/infra/EC2-PS/userna = AWS_DB_USER,
              /ifsp/infra/EC2-PS/password = AWS_DB_PASSWORD"
          withDecryption: "true"
    - name: Migrate - running
      shell: bash
      run: |
        npx sequelize-cli db:create || true
        npx sequelize-cli db:migrate
      env:
        DB_HOST: ${{ env.AWS_DB_HOST }}
        DB_USER: ${{ env.AWS_DB_USER }}
        DB_PASSWORD: ${{ env.AWS_DB_PASSWORD }}
        DB_PORT: ${{ env.AWS_DB_PORT }}
        DB_NAME: ${{ inputs.db-name }}
