name: "Serverless Deploy"
description: ""
inputs:
  stage:
    description: 'stage'
    required: true
runs:
  using: "composite"
  steps:
    - name: Serverless Deploy
      shell: bash
      run: |
        serverless deploy --verbose -s ${{ inputs.stage }}
