Resources:
  ProductsImagesS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.imagesBucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
