name: PROD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Install PG
        run: npm install --save pg pg-hstore

      - name: AWS Configure credentials
        uses: ./devops/github-actions/aws
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Migrate Sequelize
        uses: ./devops/github-actions/migrate-sequelize
        with:
          db-name: campus_hub

      - name: Serverless Deploy
        uses: ./devops/github-actions/serverless-deploy
        with:
          stage: dev
